const HEROES = [  
    "Abel: The Panther",
    "Alfonse: Prince of Askr",
    "Alfonse: Spring Prince",
    "Alm: Hero of Prophecy",
    "Amelia: Rose of the War",
    "Anna: Commander",
    "Arden: Strong and Tough",
    "Ares: Black Knight",
    "Arthur: Hapless Hero",
    "Arvis: Emperor of Flame",
    "Athena: Borderland Sword",
    "Ayra: Astra's Wielder",
    "Azama: Carefree Monk",
    "Azura: Celebratory Spirit",
    "Azura: Lady of Ballads",
    "Azura: Lady of the Lake",
    "Barst: The Hatchet",
    "Bartre: Fearless Warrior",
    "Berkut: Prideful Prince",
    "Beruka: Quiet Assassin",
    "Black Knight: Sinister General",
    "Boey: Skillful Survivor",
    "Caeda: Talys's Bride",
    "Caeda: Talys's Heart",
    "Cain: The Bull",
    "Camilla: Bewitching Beauty",
    "Camilla: Holiday Traveler",
    "Camilla: Spring Princess",
    "Camus: Sable Knight",
    "Catria: Middle Whitewing",
    "Catria: Spring Whitewing",
    "Cecilia: Etrurian General",
    "Celica: Caring Princess",
    "Celica: Imprisoned Soul",
    "Charlotte: Money Maiden",
    "Cherche: Wyvern Friend",
    "Chrom: Exalted Prince",
    "Chrom: Gifted Leader",
    "Chrom: Knight Exalt",
    "Chrom: Spring Exalt",
    "Clair: Highborn Flier",
    "Clarine: Refined Noble",
    "Clarisse: Sniper in the Dark",
    "Clive: Idealistic Knight",
    "Cordelia: Knight Paragon",
    "Cordelia: Perfect Bride",
    "Corrin: Enjoying Tradition",
    "Corrin: Fateful Prince",
    "Corrin: Fateful Princess",
    "Corrin: Novice Vacationer",
    "Deirdre: Lady of the Forest",
    "Delthea: Free Spirit",
    "Donnel: Village Hero",
    "Dorcas: Serene Warrior",
    "Draug: Gentle Giant",
    "Effie: Army of One",
    "Eirika: Anamnesis Lady",
    "Eirika: Restoration Lady",
    "Eldigan: Lionheart",
    "Elincia: Lost Princess",
    "Elise: Budding Flower",
    "Elise: Tropical Flower",
    "Eliwood: Devoted Love",
    "Eliwood: Knight of Lycia",
    "Ephraim: Legendary Lord",
    "Ephraim: Restoration Lord",
    "Est: Junior Whitewing",
    "Fae: Divine Dragon",
    "Faye: Devoted Heart",
    "Felicia: Maid Mayhem",
    "Finn: Lance of Legend",
    "Fir: Sword Student",
    "Fjorm: Princess of Ice",
    "Florina: Lovely Flier",
    "Frederick: Horizon Watcher",
    "Frederick: Polite Knight",
    "Gaius: Candy Stealer",
    "Gaius: Thief Exposed",
    "Genny: Endearing Ally",
    "Gerome: Masked Rider",
    "Gordin: Altean Archer",
    "Gray: Wry Comrade",
    "Gunnthrá: Voice of Dreams",
    "Gunter: Inveterate Soldier",
    "Gwendolyn: Adorable Knight",
    "Hana: Focused Samurai",
    "Hardin: Dark Emperor",
    "Hawkeye: Desert Guardian",
    "Hector: General of Ostia",
    "Hector: Just Here to Fight",
    "Henry: Happy Vampire",
    "Henry: Twisted Mind",
    "Hinata: Wild Samurai",
    "Hinoka: Blue Sky Warrior",
    "Hinoka: Warrior Princess",
    "Ike: Brave Mercenary",
    "Ike: Vanguard Legend",
    "Ike: Young Mercenary",
    "Inigo: Indigo Dancer",
    "Innes: Regal Strategician",
    "Ishtar: Thunder Goddess",
    "Jaffar: Angel of Death",
    "Jagen: Veteran Knight",
    "Jakob: Devoted Monster",
    "Jakob: Devoted Servant",
    "Jeorge: Perfect Shot",
    "Joshua: Tempest King",
    "Julia: Naga's Blood",
    "Julius: Scion of Darkness",
    "Kagero: Honorable Ninja",
    "Kagero: Spring Ninja",
    "Kana: Dragon Princess",
    "Kana: Dragon Spawn",
    "Karel: Sword Demon",
    "Katarina: Wayward One",
    "Kaze: Easygoing Ninja",
    "Klein: Silver Nobleman",
    "L'Arachel: Princess of Light",
    "Lachesis: Lionheart's Sister",
    "Laslow: Dancing Duelist",
    "Legion: Masked Maniac",
    "Leif: Prince of Leonster",
    "Lene: Yearning Dancer",
    "Leo: Seashore's Prince",
    "Leo: Sorcerous Prince",
    "Leon: True of Heart",
    "Lilina: Blush of Youth",
    "Lilina: Delightful Noble",
    "Linde: Light Mage",
    "Lissa: Pure Joy",
    "Lissa: Sprightly Cleric",
    "Lloyd: White Wolf",
    "Lon'qu: Solitary Blade",
    "Lucina: Brave Princess",
    "Lucina: Future Witness",
    "Lucina: Spring Exalt",
    "Lucius: The Light",
    "Lukas: Sharp Soldier",
    "Luke: Rowdy Squire",
    "Lute: Prodigy",
    "Lyn: Brave Lady",
    "Lyn: Bride of the Plains",
    "Lyn: Lady of the Plains",
    "Lyn: Lady of the Wind",
    "Lyn: Wind's Embrace",
    "Lyon: Shadow Prince",
    "Mae: Bundle of Energy",
    "Maria: Minerva's Sister",
    "Marisa: Crimson Flash",
    "Marth: Altean Groom",
    "Marth: Altean Prince",
    "Marth: Enigmatic Blade",
    "Mathilda: Legendary Knight",
    "Matthew: Faithful Spy",
    "Merric: Wind Mage",
    "Mia: Lady of Blades",
    "Micaiah: Priestess of Dawn",
    "Michalis: Ambitious King",
    "Minerva: Red Dragoon",
    "Mist: Helpful Sister",
    "Morgan: Lad from Afar",
    "Morgan: Lass from Afar",
    "Myrrh: Great Dragon",
    "Nanna: Nordion Princess",
    "Narcian: Wyvern General",
    "Navarre: Scarlet Sword",
    "Nephenee: Fierce Halberdier",
    "Niles: Cruel to Be Kind",
    "Ninian: Bright-Eyed Bride",
    "Ninian: Oracle of Destiny",
    "Nino: Pious Mage",
    "Nowi: Eternal Witch",
    "Nowi: Eternal Youth",
    "Oboro: Fierce Fighter",
    "Odin: Potent Force",
    "Ogma: Loyal Blade",
    "Oliver: Admirer of Beauty",
    "Olivia: Blushing Beauty",
    "Olivia: Festival Dancer",
    "Olwen: Blue Mage Knight",
    "Olwen: Righteous Knight",
    "Oscar: Agile Horseman",
    "Palla: Eldest Whitewing",
    "Peri: Playful Slayer",
    "Priscilla: Delicate Princess",
    "Raigh: Dark Child",
    "Raven: Peerless Fighter",
    "Rebecca: Wildflower",
    "Reinhardt: Thunder's Fist",
    "Reinhardt: Thunder's Sword",
    "Rhajat: Black Magician",
    "Robin: Fell Reincarnation",
    "Robin: Fell Vessel",
    "Robin: Festive Tactician",
    "Robin: High Deliverer",
    "Robin: Mystery Tactician",
    "Robin: Seaside Tactician",
    "Roderick: Steady Squire",
    "Roy: Brave Lion",
    "Roy: Young Lion",
    "Roy: Youthful Gifts",
    "Ryoma: Peerless Samurai",
    "Ryoma: Supreme Samurai",
    "Saber: Driven Mercenary",
    "Saias: Bishop of Flame",
    "Saizo: Angry Ninja",
    "Sakura: Gentle Nekomata",
    "Sakura: Loving Priestess",
    "Sanaki: Apostle in White",
    "Sanaki: Begnion's Apostle",
    "Selena: Cutting Wit",
    "Seliph: Heir of Light",
    "Serra: Outspoken Cleric",
    "Seth: Silver Knight",
    "Setsuna: Absent Archer",
    "Shanna: Sprightly Flier",
    "Sharena: Princess of Askr",
    "Sharena: Spring Princess",
    "Sheena: Princess of Gra",
    "Shigure: Dark Sky Singer",
    "Shigure: Uplifting Artist",
    "Shiro: Raw Talent",
    "Siegbert: Future King",
    "Sigurd: Holy Knight",
    "Soleil: Adorable Adorer",
    "Sonya: Vengeful Mage",
    "Sophia: Nabata Prophet",
    "Soren: Shrewd Strategist",
    "Sothe: Zephyr",
    "Stahl: Viridian Knight",
    "Subaki: Perfect Expert",
    "Sully: Crimson Knight",
    "Tailtiu: Thunder Noble",
    "Takumi: Empty Vessel",
    "Takumi: Prince of Soup",
    "Takumi: Wild Card",
    "Tana: Winged Princess",
    "Tharja: Normal Girl",
    "Tharja: Dark Shadow",
    "Tharja: Obsessive Bride",
    "Tiki: Dragon Scion",
    "Tiki: Naga's Voice",
    "Tiki: Summering Scion",
    "Titania: Mighty Mercenary",
    "Tobin: The Clueless One",
    "Ursula: Blue Crow",
    "Valter: Dark Moonstone",
    "Virion: Elite Archer",
    "Wrys: Kindly Priest",
    "Xander: Paragon Knight",
    "Xander: Spring Prince",
    "Xander: Student Swimmer",
    "Zelgius: Jet-Black General",
    "Zephiel: The Liberator"
 ]